"use client"

import { useState } from "react"
import { Edit, Plus, Save, Trash2 } from "lucide-react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"

type Service = { id: string; title: string; slug: string; description: string; icon: string; order: number; isActive: boolean }
const empty = { title: "", slug: "", description: "", icon: "Building2", order: 0, isActive: true }
export function ServicesManager({ initialServices }: { initialServices: Service[] }) {
  const [services, setServices] = useState(initialServices), [editing, setEditing] = useState<Service | null>(null), [form, setForm] = useState(empty), [open, setOpen] = useState(false)
  const start = (service?: Service) => { setEditing(service || null); setForm(service ? { ...service } : { ...empty, order: services.length + 1 }); setOpen(true) }
  const save = async () => { const response = await fetch("/api/services", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing ? { id: editing.id, ...form } : form) }); const result = await response.json(); if (!response.ok) return toast.error(result.error || "Could not save service"); setServices((current) => (editing ? current.map((service) => service.id === result.id ? result : service) : [...current, result]).sort((first, second) => first.order - second.order)); setOpen(false); toast.success("Service saved") }
  const remove = async (service: Service) => { if (!confirm(`Archive ${service.title}?`)) return; const response = await fetch(`/api/services?id=${service.id}`, { method: "DELETE" }); if (!response.ok) return toast.error("Could not archive service"); setServices((current) => current.map((item) => item.id === service.id ? { ...item, isActive: false } : item)); toast.success("Service archived") }
  return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-semibold">Services</h1><p className="text-muted-foreground">Edit services and their display order.</p></div><Button onClick={() => start()}><Plus className="mr-2 size-4" />Add service</Button></div><div className="grid gap-4">{services.map((service) => <Card key={service.id} className={!service.isActive ? "opacity-60" : ""}><CardContent className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div><div className="flex items-center gap-3"><span className="rounded bg-secondary/20 px-2 py-1 text-xs">#{service.order}</span><h2 className="font-semibold">{service.title}</h2>{!service.isActive && <span className="text-xs text-muted-foreground">Inactive</span>}</div><p className="mt-2 max-w-3xl text-sm text-muted-foreground">{service.description}</p></div><div className="flex shrink-0 gap-1"><Button size="icon" variant="ghost" onClick={() => start(service)}><Edit className="size-4" /></Button><Button size="icon" variant="ghost" onClick={() => remove(service)}><Trash2 className="size-4 text-destructive" /></Button></div></CardContent></Card>)}</div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing ? "Edit service" : "New service"}</DialogTitle></DialogHeader><div className="space-y-4"><Field label="Title"><Input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value, slug: form.slug || event.target.value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") })} /></Field><Field label="Slug"><Input value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value })} /></Field><Field label="Icon name"><Input value={form.icon} onChange={(event) => setForm({ ...form, icon: event.target.value })} /></Field><Field label="Display order"><Input type="number" value={form.order} onChange={(event) => setForm({ ...form, order: Number(event.target.value) })} /></Field><Field label="Description"><Textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></Field><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={save}><Save className="mr-2 size-4" />Save</Button></div></div></DialogContent></Dialog></div>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div> }
