"use client"

import { useState } from "react"
import { Edit, Plus, Star, Trash2 } from "lucide-react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Checkbox } from "@/components/ui/checkbox"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"

type Testimonial = { id: string; name: string; role?: string | null; content: string; rating: number; avatar?: string | null; isActive: boolean }
const empty = { name: "", role: "", content: "", rating: 5, avatar: "", isActive: true }
export function TestimonialsManager({ initialTestimonials }: { initialTestimonials: Testimonial[] }) {
  const [testimonials, setTestimonials] = useState(initialTestimonials), [editing, setEditing] = useState<Testimonial | null>(null), [form, setForm] = useState(empty), [open, setOpen] = useState(false)
  const start = (testimonial?: Testimonial) => { setEditing(testimonial || null); setForm(testimonial ? { ...testimonial, role: testimonial.role || "", avatar: testimonial.avatar || "" } : empty); setOpen(true) }
  const save = async () => { const payload = { ...form, avatar: form.avatar || null }; const response = await fetch("/api/testimonials", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing ? { id: editing.id, ...payload } : payload) }); const result = await response.json(); if (!response.ok) return toast.error(result.error || "Could not save testimonial"); setTestimonials((current) => editing ? current.map((item) => item.id === result.id ? result : item) : [result, ...current]); setOpen(false); toast.success("Testimonial saved") }
  const remove = async (testimonial: Testimonial) => { if (!confirm(`Archive testimonial from ${testimonial.name}?`)) return; const response = await fetch(`/api/testimonials?id=${testimonial.id}`, { method: "DELETE" }); if (!response.ok) return toast.error("Could not archive testimonial"); setTestimonials((current) => current.map((item) => item.id === testimonial.id ? { ...item, isActive: false } : item)); toast.success("Testimonial archived") }
  return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-3xl font-semibold">Testimonials</h1><p className="text-muted-foreground">Manage customer feedback shown across the site.</p></div><Button onClick={() => start()}><Plus className="mr-2 size-4" />Add testimonial</Button></div><div className="grid gap-4 lg:grid-cols-2">{testimonials.map((testimonial) => <Card key={testimonial.id} className={!testimonial.isActive ? "opacity-60" : ""}><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="font-semibold">{testimonial.name}</p><p className="text-sm text-muted-foreground">{testimonial.role || "Client"}</p></div><div className="flex">{Array.from({ length: testimonial.rating }, (_, index) => <Star key={index} className="size-4 fill-secondary text-secondary" />)}</div></div><p className="mt-4 text-sm leading-6 text-muted-foreground">{testimonial.content}</p><div className="mt-4 flex justify-end gap-1"><Button size="sm" variant="ghost" onClick={() => start(testimonial)}><Edit className="mr-1 size-4" />Edit</Button><Button size="sm" variant="ghost" onClick={() => remove(testimonial)}><Trash2 className="mr-1 size-4 text-destructive" />Archive</Button></div></CardContent></Card>)}</div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing ? "Edit testimonial" : "New testimonial"}</DialogTitle></DialogHeader><div className="space-y-4"><Field label="Name"><Input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field><Field label="Role"><Input value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })} /></Field><Field label="Avatar URL (optional)"><Input value={form.avatar} onChange={(event) => setForm({ ...form, avatar: event.target.value })} /></Field><Field label="Rating"><Input type="number" min="1" max="5" value={form.rating} onChange={(event) => setForm({ ...form, rating: Number(event.target.value) })} /></Field><Field label="Testimonial"><Textarea value={form.content} onChange={(event) => setForm({ ...form, content: event.target.value })} /></Field><label className="flex items-center gap-2 text-sm"><Checkbox checked={form.isActive} onCheckedChange={(value) => setForm({ ...form, isActive: value === true })} />Visible on website</label><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={save}>Save</Button></div></div></DialogContent></Dialog></div>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div> }
